from __future__ import annotations
import argparse,json,tempfile,hashlib
from pathlib import Path
from research.study02_protocol_integrity.scripts import freeze_protocol,generate_locked_specs,validate_study
from research.study02_protocol_integrity.scripts.locked_executor import run as locked,_result_row,_manifest
from research.study02_protocol_integrity.core.execution_contract import ExecutionAttemptContract
from research.study02_protocol_integrity.core.ruflex_subject import execute_attempt
from research.study02_protocol_integrity.core.scenario_materialization import materialize_plan
ROOT=Path(__file__).resolve().parents[1]
def dev():
 plans=[json.loads(line) for line in (ROOT/'artifacts/manifests/locked_execution_plan.jsonl').read_text().splitlines()]
 selected=[plan for family in ('V01','V06','V07') for plan in [x for x in plans if x['family']==family][:3]]
 manifest=_manifest(); rows=[]
 with tempfile.TemporaryDirectory(prefix='study02-dev-') as temp:
  for plan in selected:
   for key in ('clean_execution_contract','corrupt_execution_contract'):
    contract=ExecutionAttemptContract.from_payload(dict(plan[key])); observed=execute_attempt(contract,Path(temp)/contract.scenario_id,materialize_plan(plan))
    rows.append(_result_row(contract=contract,plan=plan,observed=observed,manifest=manifest))
 (ROOT/'artifacts/raw/dev_real_subject_results.json').write_text(''.join(json.dumps(row,sort_keys=True)+'\n' for row in rows))
 summary={'status':'PRODUCT_BACKED_DEV','pairs':len(selected),'rows':len(rows),'families':['V01','V06','V07'],'clean_false_blocks':sum(row['false_block'] for row in rows if row['clean_or_corrupt']=='clean'),'clean_false_warnings':sum(row['false_warning'] for row in rows if row['clean_or_corrupt']=='clean'),'outcomes':{family:{role:next(row['product_outcome'] for row in rows if row['family']==family and row['clean_or_corrupt']==role) for role in ('clean','corrupt')} for family in ('V01','V06','V07')}}
 (ROOT/'artifacts/aggregated/dev_native_report.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+'\n')
 historical=ROOT/'artifacts/aggregated/dev_report.json'
 old=json.loads(historical.read_text()); old.update({'status':'SUPERSEDED_HARNESS_ONLY','reason':'Generated by generic research harness before native Product V1.0.1 capability contraction. Excluded from primary evidence.'}); historical.write_text(json.dumps(old,indent=2,sort_keys=True)+'\n')
 oracle=[]
 for row in rows: oracle.append({'scenario_id':row['scenario_id'],'pair_id':row['pair_id'],'clean_or_corrupt':row['clean_or_corrupt'],'violation_family':None if row['clean_or_corrupt']=='clean' else row['family'],'expected_severity':'BLOCK' if row['clean_or_corrupt']=='corrupt' else None,'base_scenario_hash':hashlib.sha256(row['pair_id'].encode()).hexdigest()})
 (ROOT/'oracle/scenario_ground_truth.jsonl').write_text(''.join(json.dumps(x,sort_keys=True)+'\n' for x in oracle)); print(json.dumps(summary,sort_keys=True))
def main():
 p=argparse.ArgumentParser();p.add_argument('command',choices=['audit','dev','freeze','locked','aggregate','figures','validate']);a=p.parse_args()
 if a.command in {'audit','dev'}:dev()
 elif a.command=='freeze':generate_locked_specs.main();freeze_protocol.main()
 elif a.command=='locked':locked()
 elif a.command in {'aggregate','figures'}:print(json.dumps({'status':'NOT_APPLICABLE_PRE_UNLOCK'}))
 else:validate_study.main()
if __name__=='__main__':main()
