import { expect, test } from "@playwright/test";
import { tmpdir } from "node:os";
import { join } from "node:path";
test("PRODUCT-10 persists AssuranceCase independent gates without a trust score", async ({ page }) => {
  const path=join(tmpdir(),`ruflex-assurance-${Date.now()}`); await page.goto("/"); await page.getByLabel("Project path").fill(path); await page.getByLabel("Project name").fill("Assurance route"); await page.getByRole("button",{name:"Create project",exact:true}).click();
  await page.getByRole("button",{name:/Data.*No dataset/}).click(); await page.getByLabel("CSV data").fill("temperature,target\n10,0\n20,1\n30,1\n40,1\n"); await page.getByRole("button",{name:"Inspect dataset",exact:true}).click(); await page.getByRole("button",{name:"Confirm dataset contract",exact:true}).click();
  await page.getByRole("button",{name:"E",exact:true}).click();
  let assuranceJobPosts = 0;
  await page.route("**/api/projects/evidence/assurance-jobs", async (route) => { if (route.request().method() === "POST") assuranceJobPosts += 1; await route.continue(); });
  await page.getByRole("button",{name:"Build AssuranceCase",exact:true}).evaluate((button) => { button.dispatchEvent(new MouseEvent("click", { bubbles: true })); button.dispatchEvent(new MouseEvent("click", { bubbles: true })); });
  await expect(page.getByTestId("assurance-case")).toContainText("dataset contract"); await expect(page.getByTestId("assurance-case")).toContainText("NOT_AVAILABLE"); await expect(page.getByText("No universal trust score is produced.", {exact:true})).toBeVisible();
  expect(assuranceJobPosts).toBe(1);
  let bundleJobPosts = 0;
  await page.route("**/api/projects/evidence/verification-bundle-jobs", async (route) => { if (route.request().method() === "POST") bundleJobPosts += 1; await route.continue(); });
  await page.getByRole("button",{name:"Export and validate bundle",exact:true}).evaluate((button) => { button.dispatchEvent(new MouseEvent("click", { bubbles: true })); button.dispatchEvent(new MouseEvent("click", { bubbles: true })); });
  await expect(page.getByTestId("verification-bundle")).toContainText("SHA-256"); await expect(page.getByTestId("verification-bundle")).toContainText("Portable validation"); await expect(page.getByTestId("verification-bundle")).toContainText("PASS");
  expect(bundleJobPosts).toBe(1);
  await page.getByRole("button",{name:"Close",exact:true}).click(); await page.getByLabel("Project path").fill(path); await page.getByRole("button",{name:"Open project",exact:true}).click(); await page.getByRole("button",{name:"E",exact:true}).click(); await expect(page.getByTestId("assurance-case")).toContainText("dataset contract");
  await page.getByRole("button",{name:"P",exact:true}).click();
  const assuranceNode = page.locator(".lineage-assurance_case").first(); await expect(assuranceNode).toBeVisible(); await assuranceNode.click({force:true});
  await expect(page.getByText("Opened lineage object: AssuranceCase", {exact:true})).toBeVisible();
  await expect(page.getByTestId("assurance-case")).toContainText("dataset contract");
  await page.getByRole("button",{name:"P",exact:true}).click();
  const bundleNode = page.locator(".lineage-verification_bundle").first(); await expect(bundleNode).toBeVisible(); await bundleNode.click({force:true});
  await expect(page.getByTestId("verification-bundle-record")).toContainText("Persisted VerificationBundle");
});
