import { expect, test } from "@playwright/test";
import { tmpdir } from "node:os";
import { join } from "node:path";

test("a first-time user can persist synthetic evidence and apply a frozen final-test policy", async ({ page }) => {
  test.setTimeout(75_000);
  const path = join(tmpdir(), `ruflex-practice-route-${Date.now()}-${Math.random().toString(16).slice(2)}`);
  await page.goto("/");
  await page.getByLabel("Project path").fill(path);
  await page.getByLabel("Project name").fill("Practice route");
  await page.getByRole("button", { name: "Create project", exact: true }).click();
  await page.getByRole("button", { name: /Data.*No dataset/ }).click();

  const practice = page.getByRole("group", { name: "Synthetic practice dataset" });
  await expect(practice).toContainText("not research evidence");
  await practice.getByRole("button", { name: "Load synthetic practice CSV (80 rows)" }).click();
  await expect(page.getByLabel("CSV data")).toContainText("practice-080");
  await expect(page.getByRole("button", { name: "Confirm dataset contract", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Inspect dataset", exact: true }).click();
  await expect(page.getByText(/Rows: 80 · columns: 4/)).toBeVisible();
  await expect(page.getByRole("textbox", { name: "ID columns" })).toHaveValue("entity_id");
  await page.getByRole("button", { name: "Confirm dataset contract", exact: true }).click();
  await expect(page.getByText(/Contract: target · binary_classification/)).toBeVisible();
  await expect(practice).toHaveCount(0);
  const frozenSha = await page.locator(".data-summary code").first().textContent();
  expect(frozenSha).toBe("37b5f2a3872ec570bacd35d8e031bc8336c18db744989df332a58d827cc08399");
  await expect(page.getByTestId("synthetic-practice-provenance")).toContainText("not benchmark or research evidence");
  await expect(page.getByTestId("synthetic-practice-context")).toContainText("not benchmark or research evidence");

  await page.getByRole("button", { name: "S", exact: true }).click();
  await page.getByLabel("Training model").selectOption("logistic_regression");
  const response = page.waitForResponse((item) => item.url().endsWith("/api/projects/training/run") && item.request().method() === "POST");
  await page.getByRole("button", { name: "Run real training", exact: true }).click();
  expect((await response).status()).toBe(201);
  await expect(page.locator(".run-provenance")).toContainText("model artifact persisted");

  await page.getByRole("button", { name: "A", exact: true }).click();
  await expect(page.getByTestId("synthetic-practice-context")).toBeVisible();
  await page.getByRole("button", { name: "Save validation evidence", exact: true }).click();
  await expect(page.getByText("Validation ROC curve · raw model", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Select F1 threshold (raw)", exact: true }).click();
  await page.getByLabel("Selective confidence cutoff").fill("0.80");
  await page.getByRole("button", { name: "Save ACCEPT / REVIEW policy", exact: true }).click();
  await expect(page.getByText("REVIEW BELOW 0.80", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "E", exact: true }).click();
  await page.getByRole("button", { name: "Generate explanation", exact: true }).click();
  await expect(page.getByTestId("explanation-job")).toContainText("SUCCEEDED");
  await expect(page.getByText("POST-HOC ATTRIBUTION", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "Run explanation checks", exact: true }).click();
  await expect(page.getByText("PASSED_AVAILABLE_CHECKS", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Create and run BehaviorSpec", exact: true }).click();
  await expect(page.getByTestId("behavior-result")).toContainText("Output remains in declared range");
  await page.getByRole("button", { name: "Build AssuranceCase", exact: true }).click();
  await expect(page.getByTestId("assurance-case")).toContainText("dataset contract");
  await expect(page.getByTestId("assurance-case")).toContainText("behavior specs");
  await page.getByRole("button", { name: "Export and validate bundle", exact: true }).click();
  await expect(page.getByTestId("verification-bundle")).toContainText("Portable validation");
  await expect(page.getByTestId("verification-bundle")).toContainText("PASS");

  await page.getByRole("button", { name: "Close", exact: true }).click();
  await page.getByLabel("Project path").fill(path);
  await page.getByRole("button", { name: "Open project", exact: true }).click();
  await page.getByRole("button", { name: "target 80 rows", exact: true }).click();
  await expect(page.locator(".data-summary code").first()).toHaveText(frozenSha ?? "");
  await expect(page.getByText("Stored dataset preview", { exact: true })).toBeVisible();
  await expect(page.getByTestId("synthetic-practice-provenance")).toContainText("synthetic practice fixture");
  await expect(page.getByTestId("synthetic-practice-context")).toBeVisible();
  await page.getByRole("button", { name: "S", exact: true }).click();
  await expect(page.locator(".run-provenance")).toContainText("model artifact persisted");
  await page.getByRole("button", { name: "A", exact: true }).click();
  await expect(page.getByText("Validation ROC curve · raw model", { exact: true })).toBeVisible();
  await expect(page.getByText("REVIEW BELOW 0.80", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "E", exact: true }).click();
  await expect(page.getByTestId("explanation-job")).toContainText("SUCCEEDED");
  await expect(page.getByText("PASSED_AVAILABLE_CHECKS", { exact: true })).toBeVisible();
  await expect(page.getByTestId("behavior-result")).toContainText("Output remains in declared range");
  await expect(page.getByTestId("assurance-case")).toContainText("dataset contract");
  await page.getByRole("button", { name: "P", exact: true }).click();
  await page.locator(".lineage-verification_bundle").first().click({ force: true });
  await expect(page.getByTestId("verification-bundle-record")).toContainText("Persisted VerificationBundle");

  await page.getByRole("button", { name: "A", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Final test remains closed", exact: true })).toBeVisible();
  await page.getByText(/I confirm this policy was frozen before final-test access/).click();
  await page.getByRole("button", { name: "Evaluate frozen final test", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Final-test evidence persisted separately", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Reselect threshold", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Close", exact: true }).click();
  await page.getByLabel("Project path").fill(path);
  await page.getByRole("button", { name: "Open project", exact: true }).click();
  await page.getByRole("button", { name: "A", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Final-test evidence persisted separately", exact: true })).toBeVisible();
  await expect(page.getByTestId("synthetic-practice-context")).toBeVisible();
  await expect(page.getByRole("button", { name: "Reselect threshold", exact: true })).toBeDisabled();
});

test("synthetic practice loading is unavailable in a read-only project", async ({ page }) => {
  const path = join(tmpdir(), `ruflex-practice-readonly-${Date.now()}-${Math.random().toString(16).slice(2)}`);
  await page.goto("/");
  await page.getByLabel("Project path").fill(path);
  await page.getByLabel("Project name").fill("Read-only practice");
  await page.getByRole("button", { name: "Create project", exact: true }).click();
  await page.getByRole("button", { name: "Close", exact: true }).click();
  await page.getByLabel("Project path").fill(path);
  await page.getByRole("checkbox", { name: "Read-only", exact: true }).check();
  await page.getByRole("button", { name: "Open project", exact: true }).click();
  await page.getByRole("button", { name: /Data.*No dataset/ }).click();
  await expect(page.getByRole("group", { name: "Synthetic practice dataset" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Confirm dataset contract", exact: true })).toBeDisabled();
});
